src/routes/web.php
Route::post('/social/like', 'HomeController@likeSocial');
Route::post('/social/comment', 'HomeController@socialComment');
Route::get('/social/gettopcomments', 'HomeController@getTopComments');
Route::get('/social/getallcomments', 'HomeController@getAllComments');



Route::get('/notification','UserController@notification');
Route::post('/notification/{id}/read','UserController@notificationRead');

Route::post('/profile/service/create','UserController@servicePost')->name('services.create');
Route::post('/profile/service/edit','UserController@serviceEdit')->name('services.edit');
Route::get('/profile', 'UserController@index')->name('profile')->middleware('revalidate');
Route::post('/profile/edit', 'UserController@profileEdit')->name('profile.edit');
Route::post('/profile/image','UserController@addImage')->name('user.image');
Route::post('/profile/service/{id}/delete','UserController@serviceDelete')->name('services.destroy');
Route::get('/profile/viewallapplicants','UserController@allApplicants');

Route::get('/giftcard',function(){
	return view('landing.giftcard');
});

Route::get('/signin/facebook', 'Auth\LoginController@redirectToProvider');
Route::get('/signin/facebook/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('info/{slug}','HomeController@info');

Route::get('donation','HomeController@donation');

Route::get('/currency/set', 'HomeController@setCurrency');

Route::get('/asset/{source}/{img}/{h}/{w}',function($source,$img, $h, $w){
    try{
        $ext = explode(".",$img);
        $ext = end($ext);
        $source = str_replace('*','/',$source);
        if($w == 'auto'){
            return \Image::make(public_path($source."/".$img))->resize(null, $h, function ($constraint) {
                    $constraint->aspectRatio();
                })->response($ext);
        }
        return \Image::make(public_path($source."/".$img))->resize($h, $w)->response($ext);
    }catch(\Exception $e){
        abort(404);
    }
})->name('optimize');

//landing for admin
Route::prefix('admin')->group(function(){
	Route::get('/login','AdminAuth\LoginController@showLoginForm')->name('admin_login');
	Route::post('/login','AdminAuth\LoginController@login');
	Route::post('/logout','AdminAuth\LoginController@logout')->name('admin_logout');
	Route::post('/password/email','AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('admin_password.email');
	Route::post('/password/reset','AdminAuth\ResetPasswordController@reset');
	Route::get('/password/reset','AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('admin_password.request');
	Route::get('/password/reset/{token}','AdminAuth\ResetPasswordController@showResetForm')->name('admin_password.reset');
	
	Route::get('changepassword','AdminUserController@changepassword')->name('admin.changepassword');
	Route::post('changedpassword','AdminUserController@changedpassword')->name('admin.changedpassword');

	Route::get('/','AdminUserController@index')->name('admin_dashboard');

	Route::get('currencies/changestatus/{id}','Admin\CurrencyController@changeStatus');
	Route::resource('currencies','Admin\CurrencyController',['except'=>['show']]);

	Route::resource('countries','Admin\CountryController',['except'=>['show']]);
	Route::resource('countries/{country_id}/states','Admin\StateController',['except'=>['show']]);

	Route::get('/currentdonation','Admin\DonationContoller@currentdonation')->name('currentdonation');
	Route::get('/donations/add','Admin\DonationContoller@newdonation')->name('newdonation');
	Route::post('/donations/create','Admin\DonationContoller@create')->name('create');
	Route::delete('/donations/{id}/delete','Admin\DonationContoller@destroy')->name('destroy');
	Route::post('/updateDonationText','Admin\DonationContoller@updateDonationText')->name('updateDonationText');
	Route::post('/updateDonationPage','Admin\DonationContoller@updateDonationPage')->name('updateDonationPage');
	Route::get('donations','Admin\DonationContoller@index')->name('alldonations');

	Route::get('users/list', 'AdminUserController@allusers')->name('admin.users');
	Route::get('subscribers/list', 'AdminUserController@allsubscribers')->name('admin.subscribers');
	Route::get('activeUsers/list', 'AdminUserController@active_users')->name('admin.active_users');

	Route::get('/notifications','AdminUserController@notifications')->name('admin-notification');
	Route::get('/notifications/unseen','AdminUserController@getUnseen')->name('getUnseen');
	Route::get('/notifications/all','AdminUserController@notificationsAll');
	Route::get('/notifications/{id}','AdminUserController@notification')->name('notification');
	Route::post('/notifications/{id}/comfirm','AdminUserController@confirmDelivery')->name('confirmDelivery');
	Route::get('/item/addcategory','Admin\ItemController@addCategory');
	Route::get('/item/editcategory','Admin\ItemController@editCategory');
	Route::get('/item/removecategory','Admin\ItemController@removeCategory');
	Route::get('/item/changestatus/{id}','Admin\ItemController@changeStatus');
	Route::get('/item/images/{id}','Admin\ItemController@images');
	Route::post('/item/addimage','Admin\ItemController@addImage');
	Route::post('/item/removeimage','Admin\ItemController@removeImage');
	Route::post('/collection/updateDescription','Admin\ItemController@updateDescription');
	Route::resource('/item','Admin\ItemController');

	Route::get('config/landing','Admin\ConfigController@landingConfig');
	Route::get('config/info','Admin\ConfigController@infoConfig');
	Route::post('config/addfeatured','Admin\ConfigController@addFeatured');
	Route::post('config/removefeatured/{id}','Admin\ConfigController@removeFeatured');
	Route::get('config/removeinfo/{id}','Admin\ConfigController@removeInfo');
	Route::post('config/editinfo','Admin\ConfigController@editInfo');
	Route::post('config/addinfo','Admin\ConfigController@addInfo');

	Route::post('config/addlandingimage','Admin\ConfigController@addLandingImage');
	Route::post('config/removelandingimage','Admin\ConfigController@removeLandingImage');
	Route::get('config/editlandinglink','Admin\ConfigController@editLandingLink');
	
	Route::post('config/addfeaturedimage','Admin\ConfigController@addFeaturedImage');
	Route::post('config/addfirstfeaturedimage','Admin\ConfigController@addFirstFeaturedImage');
	Route::post('config/addsecondfeaturedimage','Admin\ConfigController@addSecondFeaturedImage');
	Route::post('config/addthirdfeaturedimage','Admin\ConfigController@addThirdFeaturedImage');
	Route::post('config/addfirstfeaturedcontent','Admin\ConfigController@addFirstFeaturedContent');
	Route::post('config/addsecondfeaturedcontent','Admin\ConfigController@addSecondFeaturedContent');
	Route::post('config/addthirdfeaturedcontent','Admin\ConfigController@addThirdFeaturedContent');
	Route::post('config/addlandingvideolink','Admin\ConfigController@addLandingVideoLink');
	Route::post('config/addlandingvideoimage','Admin\ConfigController@addLandingVideoImage');
	Route::post('config/addstorycontent','Admin\ConfigController@addStoryContent');
	Route::post('config/addstoryimage','Admin\ConfigController@addStoryImage');
	Route::post('config/addtrendingcontent','Admin\ConfigController@addTrendingContent');
	
	Route::get('config/contact','Admin\ConfigController@contact');
	Route::post('config/editcontact','Admin\ConfigController@editContact');

	Route::resource('serviceCategories','Admin\ServiceCategoryController',['except'=>['create','show','edit','update']]);
	Route::post('/serviceCategories/{id}/edit','Admin\ServiceCategoryController@update')->name('serviceCategories.update');


	Route::resource('review','Admin\ReviewController',['except'=>['create','show','update','edit']]);

	Route::get('social','Admin\SocialController@index');
	Route::post('social/edit/{id}','Admin\SocialController@edit');
	Route::post('social/addsocial','Admin\SocialController@addSocial');
	Route::get('social/removeSocial/{id}','Admin\SocialController@removeSocial');
	Route::post('social/addsocialimage','Admin\SocialController@addSocialImage');
	Route::post('social/removesocialimage','Admin\SocialController@removeSocialImage');
	Route::get('social/addcaption','Admin\SocialController@addCaption');
	Route::post('social/addlinks','Admin\SocialController@addLinks');
	Route::post('social/removelink/{id}','Admin\SocialController@removeLink');

	Route::resource('giftCards','Admin\GiftCardController',['except'=>['show','edit']]);
	Route::post('giftCards/showcode/{id}','Admin\GiftCardController@showCode');
	Route::post('giftCards/viewAll','Admin\GiftCardController@viewAll')->name('viewAll');
	
	Route::get('eCards','AdminUserController@eCards');

	Route::post('giftCards/{id}/changeStatus','Admin\GiftCardController@changeStatus')->name('gc.changeStatus');	

	Route::get('newsletter','Admin\NewsletterController@index')->name('newsletters.index');
	Route::post('newsletter/send','Admin\NewsletterController@send')->name('newsletters.send');

	Route::resource('featuredBrands', 'Admin\FeaturedBrandController',['except'=>['show']]);
	
	
	Route::post('footerBrands/{id}/edit','Admin\FooterBrandController@editCategory');
	Route::resource('footerBrands', 'Admin\FooterBrandController',['except'=>['show']]);
	
	Route::resource('agents', 'Admin\AgentController',['except'=>['show']]);
	Route::get('agents/changestatus/{id}','Admin\AgentController@changeStatus');
	Route::get('agents/{id}/purchases','Admin\AgentController@showPurchases');

	
	Route::get('invitations','Admin\InvitationController@index')->name('invitations.index');
	Route::delete('invitations/{id}/delete','Admin\InvitationController@destroy')->name('invitations.destroy');
	Route::post('invitations/reset','Admin\InvitationController@reset')->name('invitations.reset');
	Route::get('invitations/all','Admin\InvitationController@all')->name('invitations.all');

	Route::resource('agents', 'Admin\AgentController',['except'=>['show']]);
	Route::get('agents/changestatus/{id}','Admin\AgentController@changeStatus');

src/app/Agent.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Agent extends Model
{
    //
}

src/app/Http/Controllers/Admin/AgentController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Agent;
use App\Transaction;
use Session;
use Redirect;

class AgentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth:admin_user');
    }
    
    public function index()
    {
        $agents = Agent::orderBy('updated_at','desc')->get();
        return view('admin.agents.index')->with('agents',$agents);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.agents.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,array(
            'name'=>'required',
            'contact'=>'required',
            'email'=>'required',
            'agent_status' => 'required'
        ));

        $agent = new Agent;
        $agent->name = $request->name;
        $agent->contact = $request->contact;
        $agent->email = $request->email;
        $agent->agent_status=$request->agent_status;
        
        $agent->save();
        $agent->agent_code='AG-'.$agent->id;
        $agent->save();
        $request->session()->flash('success', 'New Agent Created.');
        return redirect()->route('agents.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $agent = Agent::find($id);
        
        if(!$agent) abort(404);

        return view('admin.agents.edit')->with('agent',$agent);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,array(
            'name'=>'required',
            'contact'=>'required',
            'email'=>'required',
            'agent_status' => 'required'
        ));

        $agent = Agent::find($id);
        if(!$agent) abort(404);
        
        $agent->name = $request->name;
        $agent->contact = $request->contact;
        $agent->email = $request->email;
        $agent->agent_status=$request->agent_status;

        $agent->save();

        $request->session()->flash('success', 'Agent Edited.');
        return redirect()->route('agents.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $agent = Agent::find($id);
        $agent->delete();

        $request->session()->flash('success', 'Agent Deleted.');
        return redirect()->route('agents.index');
    }
    public function changeStatus($id)
    {
        try {
    		$m=Agent::findOrFail($id);
            if($m->agent_status=="active")
                Agent::where('id',$id)->update(['agent_status'=>'dormant']);
            else
                Agent::where('id',$id)->update(['agent_status'=>'active']);
            
             Session::flash('success','SuccessFully changed the status');
        } 
        catch (Exception $e) {
               return $this->renderException($e);
        }
        return Redirect::to('/admin/agents');


    }

    public function showPurchases($id)
    {
        $agent=Agent::findOrFail($id);
        $transactions=Transaction::where('agent_code',$agent->agent_code)->where(function($q) {
                        $q->where('status','completed')->orWhere('status','shipped');
                    })->get();
      
        $purchases = [];

        foreach ($transactions as $transaction) {
            $count = 0;

            $items = json_decode($transaction->details);

            foreach ($items as $item) {
                $count += $item->quantity;
            }

            $purchase = array(
                'id' => $transaction->id,
                'customerName' => $transaction->transactionable->name,
                'status' => $transaction->status,
                'agent_code'=>$transaction->agent_code,
                'count' => $count
                );
            $purchases []= $purchase;
        }
      
        return view('admin.agents.purchaselist',compact('purchases','agent'));
    }
}

src/resources/views/admin/agents/create.blade.php
@extends('layouts.admin')
@section('body')

<div class="content">
    <div class="container-fluid">
        <div class="card">

            <div class="header">
                <a href="{{URL::to('admin/agents')}}" class="btn btn-info btn-fill pull-right" >Back</a>
                <h4 class="title">Add new Agent</h4>
            </div>
            <div class="content">
                <form class="form" method="POST" action="{{ route('agents.store') }}"  enctype="multipart/form-data">
                    {{ csrf_field() }}    
                    <div class="form-group">
                        <label>Agent Name</label>
                        <input type="text" id="name" class="form-control" name="name" required/>
                        <br>
                        <label>Email</label>
                        <input type="email" id="email" class="form-control" name="email" required/>
                        <br>
                        <label>Contact</label>
                        <input type="text" id="name" class="form-control" name="contact" required/>
                        <br>
                        <label>Status</label>
                        <select class="form-control" name="agent_status">
                            <option value="active">active</option>
                            <option value="dormant">dormant</option>
                            
                        </select>
                        <br>
                    </div>
                    
                    <div class="form-group">
                        <input type="submit" class="btn btn-success btn-fill" value="Add"/>
                    </div>

                </form>
            </div>
        
        </div>
    </div>
</div>
@endsection

src/resources/views/admin/agents/edit.blade.php
@extends('layouts.admin')
@section('body')

<div class="content">
    <div class="container-fluid">
        <div class="card">

            <div class="header">
                <a href="{{URL::to('admin/agents')}}" class="btn btn-info btn-fill pull-right" >Back</a>
                <h4 class="title">Edit Agent</h4>
            </div>
            <div class="content">
                <form class="form" method="POST" action="{{ route('agents.update',$agent->id) }}"  enctype="multipart/form-data">                            
                    <input type="hidden" name="_method" value="PATCH" >
                    {{ csrf_field() }}    
                    <div class="form-group">
                        <label>Agent Name</label>
                        <input type="text" id="name" class="form-control" name="name" value="{{ $agent->name  }}" required/>
                        <br>
                        <label>Email</label>
                        <input type="email" id="email" class="form-control" name="email" value="{{ $agent->email  }}" required/>
                        <br>
                        <label>Contact</label>
                        <input type="text" id="contact" class="form-control" name="contact" value="{{ $agent->contact  }}" required/>
                        <br>
                        <label>Status</label>
                        <select class="form-control" name="agent_status">
                            <option value="active" {{$agent->agent_status=='active'?'selected':''}}>active</option>
                            <option value="dormant" {{$agent->agent_status=='dormant'?'selected':''}}>dormant</option>
                            
                        </select>
                        <br>
                      
                    </div>
                    
                    <div class="form-group">
                        <input type="submit" class="btn btn-success btn-fill" value="Save"/>
                    </div>

                </form>
            </div>
        
        </div>
    </div>
</div>
@endsection

src/resources/views/admin/agents/index.blade.php
@extends('layouts.admin')

@section('body')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <a href="{{ route('agents.create') }}" class="btn btn-primary btn-fill btn-sm pull-right" style="margin:10px">Add New Agent</a>
                    
                    <div class="header">
                        <h4 class="title">Agents</h4>
                        <p class="category">Add, edit or remove agents</p>
                    </div>
                    <div class="content">
                            <div class="table-responsive">
                                    <table class="table table-striped table-bordered table-hover">
                                      <thead>
                                        <th>Id</th>
                                          <th>Name</th>
                                          <th>Email</th>
                                          <th>Contact</th>
                                          <th>Buisness Id</th>
                                          <th>Status</th>
                                          <th>Actions</th>
                                      </thead>
                                      <tbody>
                                          @foreach($agents as $i)
                                          <tr>
                                              <td>{{$i->id}}</td>                  
                                              <td>{{$i->name}}</td>
                                              <td>{{$i->email}}</td>
                                             
                                              <td>{{$i->contact}}</td>
                                              <td>{{$i->agent_code}}</td>
                                             
                                                <td>
                                                  <a href="{{URL::to('admin/agents/changestatus'.'/'.$i->id)}}"><span class="badge">{{$i->agent_status}}</span></a>
                                              </td>
                                              <td>
                                                  <a href="{{URL::to('admin/agents'.'/'.$i->id.'/'.'edit')}}"><span class="badge">edit</span></a>
                                                  <a href="{{URL::to('admin/agents'.'/'.$i->id.'/'.'purchases')}}"><span class="badge">view purchases</span></a>
                                                  
                                              <form method="POST" action="{{ URL::to('admin/agents'.'/'.$i->id) }}">
                                                <input name="_method" type="hidden" value="DELETE">
                                                {{ csrf_field() }}
                                                <button class="badge" type="button" id="deleteItem" border="1px"> 
                                                  delete
                                                </button>
                                              </form>
                                              
                                          
                                              </td>
                                          </tr>
                                          @endforeach
                                      </tbody>
                                    </table>
                                  </div>
                           
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

src/resources/views/admin/agents/purchaselist.blade.php
@extends('layouts.admin')

@section('body')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    
                    <div class="header">
                        <h4 class="title">{{$agent->name}} Transaction List</h4>
                    </div>
                    <div class="content">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover">
                                <thead>
                                <th>Id</th>
                                    <th>Name</th>
                                    <th>Actions</th>
                                </thead>
                                <tbody>
                                    @foreach ($purchases as $n)
                                    <tr>
                                        <th>{{ $n['id'] }}</th>
                                        <td>{{ $n['customerName'] }} purchased {{ $n['count'] }} items </td>
                                        
                                        <td><a href="{{ route('notification',$n['id']) }}" class="btn btn-simple">View Full</a></td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection